### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL at Installation,after npm install 

### ISSUE THREAD

**Issue by kabasakalis** [yearofmoo/angularjs-seed-repo#11]
I am getting this error after npm install while installing the app
I will appreciate anyone's help

```
> yearofmoo-angularjs-seed-repo@ postinstall D:\uvhosts\rest.dev\apps\angularjs-
seed-repo
> node ./node_modules/.bin/bower install


D:\uvhosts\rest.dev\apps\angularjs-seed-repo\node_modules\.bin\bower:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by kabasakalis** [comment]
Solved.In `package.json`   I   replaced
 `"postinstall": "node ./node_modules/.bin/bower install"`  with just
`"postinstall": "bower install"` . 
(I have bower installed globally).Must be a windows related issue.
Hope that helps someone.

**Comment by eeichinger** [comment]
A solution that doesn't rely on globally installed bower is

"postinstall": "node ./node_modules/bower/bin/bower install"
