### ISSUE TITLE
post install script not working

### ISSUE THREAD

**Issue by F1LT3R** [yearofmoo/angularjs-seed-repo#27]
Here is my output:

``` shell
~/repos/angularjs-seed-repo ⮀ ⭠ master ⮀ npm install
npm WARN package.json yearofmoo-angularjs-seed-repo@0.0.1 No repository field.

> execSync@1.0.2 install /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/grunt-shell-spawn/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2] Native extension compilation successful!

> phantomjs@1.9.15 install /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Download already available at /var/folders/0p/7d4r5xsd42v3vxp8l1nblp1h0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Extracting zip contents
Removing /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/0p/7d4r5xsd42v3vxp8l1nblp1h0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1422567177163/phantomjs-1.9.8-macosx -> /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs

> fsevents@0.2.1 install /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
npm WARN engine coffee-script-redux@2.0.0-beta4: wanted: {"node":"0.6.x || 0.8.x"} (current: {"node":"0.10.33","npm":"1.4.28"})

> ws@0.4.32 install /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> yearofmoo-angularjs-seed-repo@0.0.1 postinstall /Users/@f1lt3r/repos/angularjs-seed-repo
> node ./node_modules/bower/bin/bower install

bower angular-animate#1.2.5 not-cached git://github.com/angular/bower-angular-animate.git#1.2.5
bower angular-animate#1.2.5    resolve git://github.com/angular/bower-angular-animate.git#1.2.5
bower jquery#~2.0.3         not-cached git://github.com/jquery/jquery.git#~2.0.3
bower jquery#~2.0.3            resolve git://github.com/jquery/jquery.git#~2.0.3
bower angular-mocks#1.2.5   not-cached git://github.com/angular/bower-angular-mocks.git#1.2.5
bower angular-mocks#1.2.5      resolve git://github.com/angular/bower-angular-mocks.git#1.2.5
bower angular-route#1.2.5   not-cached git://github.com/angular/bower-angular-route.git#1.2.5
bower angular-route#1.2.5      resolve git://github.com/angular/bower-angular-route.git#1.2.5
bower angular#1.2.5         not-cached git://github.com/angular/bower-angular.git#1.2.5
bower angular#1.2.5            resolve git://github.com/angular/bower-angular.git#1.2.5
bower angular-animate#1.2.5      error Arguments to path.join must be strings

Stack trace:
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at GitHubResolver._checkout (/Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/lib/core/resolvers/GitHubResolver.js:54:21)
    at /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/lib/core/resolvers/GitResolver.js:69:21
    at _fulfilled (/Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/node_modules/q/q.js:760:13)
    at /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/node_modules/q/q.js:574:44
    at flush (/Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/node_modules/q/q.js:108:17)

Console trace:
Trace
    at StandardRenderer.error (/Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.updateNotifier.packageName (/Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/bin/bower:109:18)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/node_modules/q/q.js:808:24)
    at /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/node_modules/q/q.js:752:41)
    at /Users/@f1lt3r/repos/angularjs-seed-repo/node_modules/bower/node_modules/q/q.js:574:44

System info:
Bower version: 1.2.8
Node version: 0.10.33
OS: Darwin 14.0.0 x64

npm ERR! yearofmoo-angularjs-seed-repo@0.0.1 postinstall: `node ./node_modules/bower/bin/bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yearofmoo-angularjs-seed-repo@0.0.1 postinstall script.
npm ERR! This is most likely a problem with the yearofmoo-angularjs-seed-repo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/bower/bin/bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls yearofmoo-angularjs-seed-repo
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "/Users/@f1lt3r/local/bin/node" "/Users/@f1lt3r/local/bin/npm" "install"
npm ERR! cwd /Users/@f1lt3r/repos/angularjs-seed-repo
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/@f1lt3r/repos/angularjs-seed-repo/npm-debug.log
npm ERR! not ok code 0
```

**Comment by gregheth** [comment]
+1 
Any workarounds for this error?

**Comment by mfurlend** [comment]
I'd like to know the same
